### ISSUE TITLE
fdroid repo no longer being updated?

### ISSUE THREAD

**Issue by ghost** [rm3l/router-companion-android#4]
ive noticed the repo http://rm3l.org/fdroid/repo/ is no longer being updated. can you please fix this for users who want to use fdroid instead of google play? 
I also tried to log into the gitlab link so that i can contribute, http://git.rm3l.org:8888/ but it says username/password is incorrect.
Is this even the original gitlab link?

please help!

**Comment by cm-s** [comment]
@2SI3NX too bad to hear about this. `git.rm3l.org` doesn't even respond for me.
